# Generated by Django 5.0.3 on 2026-02-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_selected_color_selected_size"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
    ]
